# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HarshJha.YTuff
PackageVersion: 1.0.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: ytuff.exe
    PortableCommandAlias: ytuff
ReleaseDate: 2026-05-07
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/life2harsh/ytuff/releases/download/v1.0.3/ytuff-windows-x64.zip
    InstallerSha256: 1CE4B09BCABE2C68993260424CDED0522B951500C1AE98B4914328914F9A6A32
ManifestType: installer
ManifestVersion: 1.12.0
