# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HarshJha.YTuff
PackageVersion: 1.0.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: ytuff.exe
    PortableCommandAlias: ytuff
ReleaseDate: 2026-05-07
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/life2harsh/ytuff/releases/download/v1.0.3/ytuff-windows-x64.zip
    InstallerSha256: 159F560E2AC17CFC112527A398B4CFEBB5E17E34B3799380B10731B2DD79D56B
ManifestType: installer
ManifestVersion: 1.12.0
